title: <p align="center"> Nikhil Zodape </p>
logo: /assets/img/1648292442565.jpg

description:
  <p align="center">
  <a href="https://drive.google.com/file/d/1vGzTxuspmUy-WHmC_cu5mrDQKeKfaoUx/view?usp=sharing">Resume</a>|
  <a href="https://github.com/nikhilzodape">Github</a> |
  <a href="https://www.linkedin.com/in/nikhil-zodape/">LinkedIn</a>|
  <a href="https://public.tableau.com/app/profile/nikhil.zodape/vizzes">Tableau</a>|
  <a href="https://www.kaggle.com/nikszodape/code">Kaggle</a>
  
  <br>
  I'm working on Data Science, Machine learning, NLP-related problems, MySQL & Tableau.
  
  </br>
  </p>
  
# show_downloads: False

theme: jekyll-theme-minimal
