title: <p align="center"> Nikhil Zodape </p>
logo: /assets/img/headshot_circle.png

description:
  <p align="center">
  <a href="https://drive.google.com/file/d/1vGzTxuspmUy-WHmC_cu5mrDQKeKfaoUx/view?usp=sharing">Resume</a>|
  <a href="https://github.com/nikhilzodape">Github</a> |
  <a href="https://www.linkedin.com/in/nikhil-zodape/">LinkedIn</a>
  </p>
  
show_downloads: False

theme: jekyll-theme-minimal
